AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ruby-serverless-chrome

  SAM Template for running a headless web scraper with Ruby in AWS Lambda.

Globals:
  Api:
    BinaryMediaTypes:
      - "*~1*"

Resources:
  ScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scraper/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      MemorySize: 512
      Timeout: 30
      Events:
        Scrape:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scrape
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScraperApi:
    Description: "API Gateway endpoint URL for Prod stage for Scraper function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrape/"
  ScraperFunction:
    Description: "Scraper Lambda Function ARN"
    Value: !GetAtt ScraperFunction.Arn
  ScraperFunctionIamRole:
    Description: "Implicit IAM Role created for Scraper function"
    Value: !GetAtt ScraperFunctionRole.Arn
